Import Libraries

In [ ]:
import pandas as pd
import numpy as np

Import the Job Posting Dataset

In [ ]:
df = pd.read_csv("/content/job_postings.csv")

Check the data

In [ ]:
df.head()

,job_link,last_processed_time,last_status,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type
0,https://www.linkedin.com/jobs/view/senior-mach...,2024-01-21 08:08:48.031964+00,Finished NER,t,t,f,Senior Machine Learning Engineer,Jobs for Humanity,"New Haven, CT",2024-01-14,East Haven,United States,Agricultural-Research Engineer,Mid senior,Onsite
1,https://www.linkedin.com/jobs/view/principal-s...,2024-01-20 04:02:12.331406+00,Finished NER,t,t,f,"Principal Software Engineer, ML Accelerators",Aurora,"San Francisco, CA",2024-01-14,El Cerrito,United States,Set-Key Driver,Mid senior,Onsite
2,https://www.linkedin.com/jobs/view/senior-etl-...,2024-01-21 08:08:31.941595+00,Finished NER,t,t,f,Senior ETL Data Warehouse Specialist,Adame Services LLC,"New York, NY",2024-01-14,Middletown,United States,Technical Support Specialist,Associate,Onsite
3,https://www.linkedin.com/jobs/view/senior-data...,2024-01-20 15:30:55.796572+00,Finished NER,t,t,f,Senior Data Warehouse Developer / Architect,Morph Enterprise,"Harrisburg, PA",2024-01-12,Lebanon,United States,Architect,Mid senior,Onsite
4,https://www.linkedin.com/jobs/view/lead-data-e...,2024-01-21 08:08:58.312124+00,Finished NER,t,t,f,Lead Data Engineer,Dice,"Plano, TX",2024-01-14,McKinney,United States,Maintenance Data Analyst,Mid senior,Onsite

Count top 20 job titles

In [ ]:
top_10= df["job_title"].value_counts()

In [ ]:
top_10[:20]

job_title
Senior Data Engineer                                        285
Senior Data Analyst                                         163
Data Engineer                                               149
Senior MLOps Engineer                                       138
Data Analyst                                                137
Data Scientist                                              128
Lead Data Engineer                                          123
Senior Data Scientist                                       119
Data Architect                                              111
Staff Machine Learning Engineer, Series A                   101
Senior Machine Learning Engineer                             59
Manager, Data Engineering                                    57
Manager, Data Loss Prevention (DLP) Engineer (Symantec)      57
Principal Associate, Data Loss Prevention (DLP) Engineer     53
Senior Machine Learning Engineer - AI                        53
Senior Data Engineer, Public Company                         53
Machine Learning Engineer                                    49
Senior Database Administrator                                49
Lead Data Scientist                                          46
Senior MLS Engineer, Autonomous Driving Startup              45
Name: count, dtype: int64

Group job titles to primary roles

In [ ]:

# Mapping dictionary (from top 20 titles → grouped roles)
mapping = {
    # Data Engineer
    "senior data engineer": "Data Engineer",
    "data engineer": "Data Engineer",
    "lead data engineer": "Data Engineer",
    "manager, data engineering": "Data Engineer",
    "senior data engineer, public company": "Data Engineer",

    # Data Analyst
    "senior data analyst": "Data Analyst",
    "data analyst": "Data Analyst",

    # Data Scientist
    "data scientist": "Data Scientist",
    "senior data scientist": "Data Scientist",
    "lead data scientist": "Data Scientist",

    # Machine Learning Engineer
    "staff machine learning engineer, series a": "Machine Learning Engineer",
    "senior machine learning engineer": "Machine Learning Engineer",
    "machine learning engineer": "Machine Learning Engineer",
    "senior machine learning engineer - ai": "Machine Learning Engineer",
    "senior mls engineer, autonomous driving startup": "Machine Learning Engineer",

    # MLOps
    "senior mlops engineer": "MLOps Engineer",

    # Data Architect / Database
    "data architect": "Data Architect / Database",
    "senior database administrator": "Data Architect / Database",

    # Data Security
    "manager, data loss prevention (dlp) engineer (symantec)": "Data Security Engineer",
    "principal associate, data loss prevention (dlp) engineer": "Data Security Engineer"
}

# Function to standardize job titles into groups
def map_job_title(title):
    title_lower = title.lower()
    for key, value in mapping.items():
        if key in title_lower:   # case-insensitive matching
            return value
    return "Other"  # default for all titles not in top 20

# Apply mapping
df["job_group"] = df["job_title"].apply(map_job_title)

print(df)

                                                job_link  \
0      https://www.linkedin.com/jobs/view/senior-mach...
1      https://www.linkedin.com/jobs/view/principal-s...
2      https://www.linkedin.com/jobs/view/senior-etl-...
3      https://www.linkedin.com/jobs/view/senior-data...
4      https://www.linkedin.com/jobs/view/lead-data-e...
...                                                  ...
12212  https://uk.linkedin.com/jobs/view/data-reporti...
12213  https://www.linkedin.com/jobs/view/corporate-a...
12214  https://www.linkedin.com/jobs/view/senior-data...
12215  https://www.linkedin.com/jobs/view/senior-data...
12216  https://www.linkedin.com/jobs/view/medical-tec...

                 last_processed_time   last_status got_summary got_ner  \
0      2024-01-21 08:08:48.031964+00  Finished NER           t       t
1      2024-01-20 04:02:12.331406+00  Finished NER           t       t
2      2024-01-21 08:08:31.941595+00  Finished NER           t       t
3      2024-01-20 15:30:55.796572+00  Finished NER           t       t
4      2024-01-21 08:08:58.312124+00  Finished NER           t       t
...                              ...           ...         ...     ...
12212  2024-01-21 07:11:22.099082+00  Finished NER           t       t
12213  2024-01-19 15:10:41.177008+00  Finished NER           t       t
12214  2024-01-20 15:20:19.036168+00  Finished NER           t       t
12215  2024-01-19 23:25:28.107523+00  Finished NER           t       t
12216  2024-01-19 23:26:27.593516+00  Finished NER           t       t

      is_being_worked                                     job_title  \
0                   f              Senior Machine Learning Engineer
1                   f  Principal Software Engineer, ML Accelerators
2                   f          Senior ETL Data Warehouse Specialist
3                   f   Senior Data Warehouse Developer / Architect
4                   f                            Lead Data Engineer
...               ...                                           ...
12212               f  Data Reporting Manager, FOOTBALL ASSOCIATION
12213               f  Corporate AML Alert Investigation Specialist
12214               f                         Senior Data Scientist
12215               f                          Senior Data Engineer
12216               f              Medical Technologist, MLS or MLT

                                   company                      job_location  \
0                        Jobs for Humanity                     New Haven, CT
1                                   Aurora                 San Francisco, CA
2                       Adame Services LLC                      New York, NY
3                         Morph Enterprise                    Harrisburg, PA
4                                     Dice                         Plano, TX
...                                    ...                               ...
12212                        Guardian Jobs  Wembley, England, United Kingdom
12213                Glacier Bancorp, Inc.                     Kalispell, MT
12214                             Highnote                 San Francisco, CA
12215  CompSource Mutual Insurance Company                 Oklahoma City, OK
12216             Community Health Systems                   Mooresville, NC

       first_seen   search_city  search_country  \
0      2024-01-14    East Haven   United States
1      2024-01-14    El Cerrito   United States
2      2024-01-14    Middletown   United States
3      2024-01-12       Lebanon   United States
4      2024-01-14      McKinney   United States
...           ...           ...             ...
12212  2024-01-16  High Wycombe  United Kingdom
12213  2024-01-14       Montana   United States
12214  2024-01-16    San Rafael   United States
12215  2024-01-16       Arcadia   United States
12216  2024-01-14     Salisbury   United States

                      search_position   job_level job_type  \
0      Agricultural-Research Engineer  Mid senior   Onsite
1                      Set-Key Driver  Mid senior   Onsite
2        Technical Support Specialist   Associate   Onsite
3                           Architect  Mid senior   Onsite
4            Maintenance Data Analyst  Mid senior   Onsite
...                               ...         ...      ...
12212          Manager Forms Analysis  Mid senior   Onsite
12213                          Teller  Mid senior   Onsite
12214                   Mathematician  Mid senior   Onsite
12215             Protection Engineer  Mid senior   Onsite
12216                       Biologist  Mid senior   Onsite

                       job_group
0      Machine Learning Engineer
1                          Other
2                          Other
3                          Other
4                  Data Engineer
...                          ...
12212                      Other
12213                      Other
12214             Data Scientist
12215              Data Engineer
12216                      Other

[12217 rows x 16 columns]

In [ ]:
df

,job_link,last_processed_time,last_status,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type,job_group
0,https://www.linkedin.com/jobs/view/senior-mach...,2024-01-21 08:08:48.031964+00,Finished NER,t,t,f,Senior Machine Learning Engineer,Jobs for Humanity,"New Haven, CT",2024-01-14,East Haven,United States,Agricultural-Research Engineer,Mid senior,Onsite,Machine Learning Engineer
1,https://www.linkedin.com/jobs/view/principal-s...,2024-01-20 04:02:12.331406+00,Finished NER,t,t,f,"Principal Software Engineer, ML Accelerators",Aurora,"San Francisco, CA",2024-01-14,El Cerrito,United States,Set-Key Driver,Mid senior,Onsite,Other
2,https://www.linkedin.com/jobs/view/senior-etl-...,2024-01-21 08:08:31.941595+00,Finished NER,t,t,f,Senior ETL Data Warehouse Specialist,Adame Services LLC,"New York, NY",2024-01-14,Middletown,United States,Technical Support Specialist,Associate,Onsite,Other
3,https://www.linkedin.com/jobs/view/senior-data...,2024-01-20 15:30:55.796572+00,Finished NER,t,t,f,Senior Data Warehouse Developer / Architect,Morph Enterprise,"Harrisburg, PA",2024-01-12,Lebanon,United States,Architect,Mid senior,Onsite,Other
4,https://www.linkedin.com/jobs/view/lead-data-e...,2024-01-21 08:08:58.312124+00,Finished NER,t,t,f,Lead Data Engineer,Dice,"Plano, TX",2024-01-14,McKinney,United States,Maintenance Data Analyst,Mid senior,Onsite,Data Engineer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12212,https://uk.linkedin.com/jobs/view/data-reporti...,2024-01-21 07:11:22.099082+00,Finished NER,t,t,f,"Data Reporting Manager, FOOTBALL ASSOCIATION",Guardian Jobs,"Wembley, England, United Kingdom",2024-01-16,High Wycombe,United Kingdom,Manager Forms Analysis,Mid senior,Onsite,Other
12213,https://www.linkedin.com/jobs/view/corporate-a...,2024-01-19 15:10:41.177008+00,Finished NER,t,t,f,Corporate AML Alert Investigation Specialist,"Glacier Bancorp, Inc.","Kalispell, MT",2024-01-14,Montana,United States,Teller,Mid senior,Onsite,Other
12214,https://www.linkedin.com/jobs/view/senior-data...,2024-01-20 15:20:19.036168+00,Finished NER,t,t,f,Senior Data Scientist,Highnote,"San Francisco, CA",2024-01-16,San Rafael,United States,Mathematician,Mid senior,Onsite,Data Scientist
12215,https://www.linkedin.com/jobs/view/senior-data...,2024-01-19 23:25:28.107523+00,Finished NER,t,t,f,Senior Data Engineer,CompSource Mutual Insurance Company,"Oklahoma City, OK",2024-01-16,Arcadia,United States,Protection Engineer,Mid senior,Onsite,Data Engineer
12216,https://www.linkedin.com/jobs/view/medical-tec...,2024-01-19 23:26:27.593516+00,Finished NER,t,t,f,"Medical Technologist, MLS or MLT",Community Health Systems,"Mooresville, NC",2024-01-14,Salisbury,United States,Biologist,Mid senior,Onsite,Other

In [ ]:
df["index"] = range(1, len(df) + 1)

In [ ]:
df=df.drop(columns="index")

Reformat the date

In [ ]:
df["date"] = pd.to_datetime(df["last_processed_time"]).dt.date

In [ ]:
df=df.drop(columns="last_processed_time")
df.rename(columns ={"date":"last_processed_time"}, inplace=True)

In [ ]:
df

,job_link,last_status,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type,job_group,last_processed_time
0,https://www.linkedin.com/jobs/view/senior-mach...,Finished NER,t,t,f,Senior Machine Learning Engineer,Jobs for Humanity,"New Haven, CT",2024-01-14,East Haven,United States,Agricultural-Research Engineer,Mid senior,Onsite,Machine Learning Engineer,2024-01-21
1,https://www.linkedin.com/jobs/view/principal-s...,Finished NER,t,t,f,"Principal Software Engineer, ML Accelerators",Aurora,"San Francisco, CA",2024-01-14,El Cerrito,United States,Set-Key Driver,Mid senior,Onsite,Other,2024-01-20
2,https://www.linkedin.com/jobs/view/senior-etl-...,Finished NER,t,t,f,Senior ETL Data Warehouse Specialist,Adame Services LLC,"New York, NY",2024-01-14,Middletown,United States,Technical Support Specialist,Associate,Onsite,Other,2024-01-21
3,https://www.linkedin.com/jobs/view/senior-data...,Finished NER,t,t,f,Senior Data Warehouse Developer / Architect,Morph Enterprise,"Harrisburg, PA",2024-01-12,Lebanon,United States,Architect,Mid senior,Onsite,Other,2024-01-20
4,https://www.linkedin.com/jobs/view/lead-data-e...,Finished NER,t,t,f,Lead Data Engineer,Dice,"Plano, TX",2024-01-14,McKinney,United States,Maintenance Data Analyst,Mid senior,Onsite,Data Engineer,2024-01-21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12212,https://uk.linkedin.com/jobs/view/data-reporti...,Finished NER,t,t,f,"Data Reporting Manager, FOOTBALL ASSOCIATION",Guardian Jobs,"Wembley, England, United Kingdom",2024-01-16,High Wycombe,United Kingdom,Manager Forms Analysis,Mid senior,Onsite,Other,2024-01-21
12213,https://www.linkedin.com/jobs/view/corporate-a...,Finished NER,t,t,f,Corporate AML Alert Investigation Specialist,"Glacier Bancorp, Inc.","Kalispell, MT",2024-01-14,Montana,United States,Teller,Mid senior,Onsite,Other,2024-01-19
12214,https://www.linkedin.com/jobs/view/senior-data...,Finished NER,t,t,f,Senior Data Scientist,Highnote,"San Francisco, CA",2024-01-16,San Rafael,United States,Mathematician,Mid senior,Onsite,Data Scientist,2024-01-20
12215,https://www.linkedin.com/jobs/view/senior-data...,Finished NER,t,t,f,Senior Data Engineer,CompSource Mutual Insurance Company,"Oklahoma City, OK",2024-01-16,Arcadia,United States,Protection Engineer,Mid senior,Onsite,Data Engineer,2024-01-19
12216,https://www.linkedin.com/jobs/view/medical-tec...,Finished NER,t,t,f,"Medical Technologist, MLS or MLT",Community Health Systems,"Mooresville, NC",2024-01-14,Salisbury,United States,Biologist,Mid senior,Onsite,Other,2024-01-19

Import the job skill dataset

In [ ]:
df_1=pd.read_csv("/content/job_skills.csv")

Check the data

In [ ]:
df_1.head()

,job_link,job_skills
0,https://www.linkedin.com/jobs/view/senior-mach...,"Machine Learning, Programming, Python, Scala, ..."
1,https://www.linkedin.com/jobs/view/principal-s...,"C++, Python, PyTorch, TensorFlow, MXNet, CUDA,..."
2,https://www.linkedin.com/jobs/view/senior-etl-...,"ETL, Data Integration, Data Transformation, Da..."
3,https://www.linkedin.com/jobs/view/senior-data...,"Data Lakes, Data Bricks, Azure Data Factory Pi..."
4,https://www.linkedin.com/jobs/view/lead-data-e...,"Java, Scala, Python, RDBMS, NoSQL, Redshift, S..."

Cleansed and standardized a column of comma-separated job skills, identified the top 10 most frequent skills, and created one-hot encoded columns for those skills in the original dataframe

In [ ]:

# 1. Ensure list of skills is ready
df_1["job_skills_list"] = df_1["job_skills"].fillna("").str.split(",").apply(
    lambda x: [s.strip().lower() for s in x if s.strip() != ""]
)

# 2. Explode into long format
df_long = df_1.explode("job_skills_list").reset_index()
df_long.rename(columns={"index": "row_id"}, inplace=True)

# 3. Count frequencies
skills_count = df_long["job_skills_list"].value_counts()
top_10_skills = skills_count.head(10).index.tolist()
# Another way: top_10_skills = skills_count.index [:10].tolist()

# 4. Create dummy (one-hot) columns only for top 10
for skill in top_10_skills:
    df_1[skill] = df_1["job_skills_list"].apply(lambda skills: int(skill in skills))

print(df_1.head())

In [ ]:
df_1

,job_link,job_skills,job_skills_list,python,sql,data analysis,machine learning,communication,data visualization,aws,project management,data engineering,communication skills
0,https://www.linkedin.com/jobs/view/senior-mach...,"Machine Learning, Programming, Python, Scala, ...","[machine learning, programming, python, scala,...",1,0,0,1,0,1,0,0,1,0
1,https://www.linkedin.com/jobs/view/principal-s...,"C++, Python, PyTorch, TensorFlow, MXNet, CUDA,...","[c++, python, pytorch, tensorflow, mxnet, cuda...",1,0,0,0,0,0,0,0,0,1
2,https://www.linkedin.com/jobs/view/senior-etl-...,"ETL, Data Integration, Data Transformation, Da...","[etl, data integration, data transformation, d...",0,1,1,0,1,0,0,0,0,0
3,https://www.linkedin.com/jobs/view/senior-data...,"Data Lakes, Data Bricks, Azure Data Factory Pi...","[data lakes, data bricks, azure data factory p...",1,0,0,0,1,0,0,1,1,0
4,https://www.linkedin.com/jobs/view/lead-data-e...,"Java, Scala, Python, RDBMS, NoSQL, Redshift, S...","[java, scala, python, rdbms, nosql, redshift, ...",1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12212,https://uk.linkedin.com/jobs/view/data-reporti...,"Dashboard development, Reporting, Power BI, SQ...","[dashboard development, reporting, power bi, s...",0,1,0,0,1,0,0,0,0,0
12213,https://www.linkedin.com/jobs/view/corporate-a...,"Investigation, Antimoney laundering, Fraud, Ba...","[investigation, antimoney laundering, fraud, b...",0,0,0,0,1,0,0,0,0,0
12214,https://www.linkedin.com/jobs/view/senior-data...,"Data Science, Quantitative Modeling, SQL, Data...","[data science, quantitative modeling, sql, dat...",0,1,0,1,0,1,0,0,0,0
12215,https://www.linkedin.com/jobs/view/senior-data...,"Data Engineering, Data Quality, SQL, Python, T...","[data engineering, data quality, sql, python, ...",1,1,0,0,0,0,0,0,1,0
12216,https://www.linkedin.com/jobs/view/medical-tec...,"Medical Technology, MLS, Microbiology, Clinica...","[medical technology, mls, microbiology, clinic...",0,0,0,0,0,0,0,0,0,0

In [ ]:
df_1

Download the datasets

In [ ]:
df_1.to_excel("skills.xlsx", index=False)
df.to_excel("jobs.xlsx",index=False)